{% set name = "spyql" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/spyql-{{ version }}.tar.gz
  sha256: cdfaa34efe05e30591f2017489e7f3447a0c92ef9b3ccca96b2feef8d707bbae

build:
  entry_points:
    - spyql=spyql.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - asciichartpy
    - click >=7.1.2
    - python >=3.6
    - tabulate

test:
  source_files:
    - tests
  imports:
    - spyql
  commands:
    - pip check
    - spyql --help
    - pytest -vvv --capture=tee-sys tests
  requires:
    - numpy
    - orjson
    - pip
    - pytest

about:
  home: https://github.com/dcmoura/spyql
  summary: A query language that combines the structure of SQL with the power Python
  doc_url: https://spyql.readthedocs.io/en/latest/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
